import { useRef, useState } from "react";
import { View, Text, StyleSheet, Share } from "react-native";
import { TasteProfileData } from "@/lib/ai/taste-engine";
import { Button } from "@/components/shared/Button";
import { theme } from "@/constants/Theme";

interface IdentityCardProps {
  boardName: string;
  identityLabel: string;
  profileData: TasteProfileData;
}

export function IdentityCard({ boardName, identityLabel, profileData }: IdentityCardProps) {
  const [shared, setShared] = useState(false);

  const handleShare = async () => {
    const activities = profileData.activity_types?.join(", ") || "";
    const aesthetic = profileData.aesthetic || "";
    const food = profileData.food_preferences?.join(", ") || "";
    const locations = profileData.location_patterns?.join(", ") || "";
    const humour = profileData.humour_style || "";
    const price = profileData.price_range || "";

    const text = `${boardName}\n"${identityLabel}"\n\n` +
      `Into: ${activities}\n` +
      `Aesthetic: ${aesthetic}\n` +
      (food ? `Food: ${food}\n` : "") +
      (locations ? `Where: ${locations}\n` : "") +
      (humour && humour !== "not enough data yet" ? `Humour: ${humour}\n` : "") +
      (price ? `Budget: ${price}\n` : "") +
      `\nGenerated by Sendit`;

    await Share.share({ message: text });
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  return (
    <View style={styles.wrapper}>
      {/* The visual card */}
      <View style={styles.card}>
        <View style={styles.topBar} />
        <Text style={styles.boardName}>{boardName}</Text>
        <Text style={styles.identity}>{identityLabel}</Text>

        <View style={styles.divider} />

        <View style={styles.traits}>
          {profileData.activity_types?.slice(0, 4).map((a, i) => (
            <View key={i} style={styles.traitPill}>
              <Text style={styles.traitText}>{a}</Text>
            </View>
          ))}
        </View>

        {profileData.aesthetic && (
          <Text style={styles.aesthetic}>"{profileData.aesthetic}"</Text>
        )}

        <View style={styles.footer}>
          {profileData.price_range && (
            <Text style={styles.footerText}>💰 {profileData.price_range}</Text>
          )}
          {profileData.location_patterns?.[0] && (
            <Text style={styles.footerText}>📍 {profileData.location_patterns[0]}</Text>
          )}
        </View>

        <Text style={styles.branding}>sendit</Text>
      </View>

      {/* Share button */}
      <Button
        title={shared ? "Shared!" : "Share Identity"}
        onPress={handleShare}
        variant="secondary"
        style={{ marginTop: 12 }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: { marginTop: 8 },
  card: {
    backgroundColor: "#0e0c0a",
    borderRadius: 20,
    padding: 24,
    paddingTop: 0,
    overflow: "hidden",
  },
  topBar: { height: 4, backgroundColor: theme.colors.primary, marginHorizontal: -24, marginBottom: 20 },
  boardName: { fontSize: 13, color: "#6e6963", textTransform: "uppercase", letterSpacing: 2, marginBottom: 6 },
  identity: { fontSize: 24, fontWeight: "bold", color: "#eeebe3", lineHeight: 30, marginBottom: 16 },
  divider: { height: 1, backgroundColor: "rgba(238,235,227,0.1)", marginBottom: 16 },
  traits: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  traitPill: { backgroundColor: "rgba(212,86,42,0.15)", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6 },
  traitText: { fontSize: 13, color: theme.colors.primary, fontWeight: "500" },
  aesthetic: { fontSize: 15, color: "rgba(238,235,227,0.6)", fontStyle: "italic", marginBottom: 16 },
  footer: { flexDirection: "row", gap: 16, marginBottom: 16 },
  footerText: { fontSize: 13, color: "#6e6963" },
  branding: { fontSize: 11, color: "rgba(238,235,227,0.2)", textAlign: "right", letterSpacing: 2 },
});
